# Generated by Django 5.0.2 on 2024-03-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('drname', models.CharField(max_length=200, null=True)),
                ('datepicker', models.CharField(max_length=200, null=True)),
                ('symptoms', models.CharField(max_length=200)),
            ],
        ),
    ]
