# Generated by Django 5.0.2 on 2024-03-06 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_deptregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appoinment',
            old_name='name',
            new_name='patientname',
        ),
    ]
